openapi: 3.0.3
info:
  title: Financial Portfolio
  description: Financial Portfolio
  version: 1.0.0
paths:
  /v1/expenses:
    $ref: 'expense-paths.yaml#/operations/expense-operations'
  /v1/expenses/{id}:
    $ref: 'expense-paths.yaml#/operations/expense-operations-by-id'

  /v1/expense-category:
    $ref: 'expense-category-paths.yaml#/operations/expense-category-operations'
  /v1/expense-category/{id}:
    $ref: 'expense-category-paths.yaml#/operations/expense-category-operations-by-id'
