openapi: 3.0.3
info:
  title: Financial Portfolio
  description: Financial Portfolio
  version: 1.0.0
paths:
  /v1/expenses:
    $ref: 'financial-portfolio-paths.yaml#/operations/expense-operations'
  /v1/expenses/{id}:
    $ref: 'financial-portfolio-paths.yaml#/operations/expense-operations-by-id'
  
