version: '3.7'

volumes:
  postgres:
  pgadmin:
  redis:

services:
  postgresql:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: financial-portfolio
      POSTGRES_PASSWORD: password
      POSTGRES_USER: nicholaselp
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432'
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./src/main/resources/pgadmin/docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:nicholaselp:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
  redis:
    container_name: redis_container
    image: redis:latest
    volumes:
      - redis:/data/redis
    ports:
      - '6379:6379'
    restart: unless-stopped
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181